init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\myproject

# fetch repository as zip archive
shallow_clone: true                 # default is "false"

# set clone depth
clone_depth: 5                      # clone entire repository history if not defined

 matrix:
 - nodejs_version:"6"
 install:
 - ps: Install-Product node $env:nodejs_version
 - npm install

 test_script:
 - node --version
 - npm version
 - npm test
 build : off
